version: "3.9"

services:
  next:
    build:
      context: next
    networks:
      - app-network
    volumes:
      - ./next:/var/src/next
      - /var/src/next/node_modules
      - /var/src/next/.next
    ports:
      - 3001:3001
    depends_on:
      - strapi

  strapi:
    image: strapi/strapi:3.3.4-node12-alpine
    restart: always
    env_file: ./strapi/.env
    networks:
      - app-network
      - core-network
    volumes:
      - ./strapi:/var/src/strapi
    ports:
      - 1337:1337
    depends_on:
      - strapi-db

  strapi-db:
    image: mongo:4.4.2
    restart: always
    env_file: ./strapi/.env
    networks:
      - core-network
    volumes:
      - strapi-db-volume:/data/db

  updater:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.7-alpine3.8-2020-06-06
    environment:
      PORT: 1338
    restart: always
    networks:
      - core-network
    volumes:
      - ./updater:/var/src/updater
    ports:
      - 1338:1338
    depends_on:
      - strapi
      - strapi-db
      - grafana-db

  grafana:
    image: grafana/grafana:7.3.5
    restart: always
    networks:
      - monitoring-network
    volumes:
      - grafana-volume:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - grafana-db

  grafana-db:
    image: influxdb:1.8.3
    restart: always
    env_file: ./updater/.env
    networks:
      - monitoring-network
      - core-network
    volumes:
      - grafana-db-volume:/var/lib/influxdb/data

networks:
  app-network:
  core-network:
  monitoring-network:

volumes:
  strapi-db-volume:
  grafana-volume:
  grafana-db-volume:
