version: "3.9"

services:
  next:
    image: next:10.0.3
    build:
      context: next
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - ./next:/next
      # - /next/node_modules
      # - /next/.next
    ports:
      - 3001:3001
    depends_on:
      - strapi

  strapi:
    image: strapi/strapi:3.4.0-node14-alpine
    restart: unless-stopped
    env_file: ./strapi/.env
    networks:
      - app-network
      - core-network
    volumes:
      - ./strapi:/srv/app
      # - /srv/app/build
      # - /srv/app/exports/graphql
      # - /srv/app/node_modules
    ports:
      - 1337:1337
    depends_on:
      - strapidb

  strapidb:
    image: mongo:4.4.2
    restart: unless-stopped
    env_file: ./.env.strapidb
    networks:
      - core-network
    volumes:
      - strapidb-volume:/data/db
    ports:
      - 27017:27017

  updater:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.7-alpine3.8-2020-06-06
    environment:
      PORT: 1338
    restart: unless-stopped
    networks:
      - core-network
    volumes:
      - ./updater:/app
    ports:
      - 1338:1338
    depends_on:
      - strapi
      - strapidb
      - grafanadb

  grafana:
    image: grafana/grafana:7.3.5
    restart: unless-stopped
    networks:
      - monitoring-network
    volumes:
      - grafana-volume:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - grafanadb

  grafanadb:
    image: influxdb:1.8.3
    restart: unless-stopped
    env_file: ./.env.grafanadb
    networks:
      - monitoring-network
      - core-network
    volumes:
      - grafanadb-volume:/var/lib/influxdb

networks:
  app-network:
  core-network:
  monitoring-network:

volumes:
  strapidb-volume:
  grafana-volume:
  grafanadb-volume:
